# Pre-commit hooks configuration
repos:
  # Ruff - Fast Python linter and formatter (replaces black, isort, flake8)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.1.8'
    hooks:
      - id: ruff
        args: ['--fix', '--exit-non-zero-on-fix']
      - id: ruff-format

  # mypy - Static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.7.1'
    hooks:
      - id: mypy
        additional_dependencies:
          - types-toml
        args: ['--ignore-missing-imports', '--no-strict-optional']
        exclude: '^tests/'

  # Additional useful hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.5.0'
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=1000']  # 1MB limit
      - id: check-case-conflict
      - id: check-docstring-first
      - id: debug-statements
